name: Hexo Build and Deploy

on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          # recursively checkout submodules.
          #
          # When the `ssh-key` input is not provided, SSH URLs beginning with
          # `git@github.com:` are converted to HTTPS.
          #
          # Default: false
          submodules: 'recursive'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      - uses: yrpang/github-actions-hexo@v1.3
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          branch: 'gh-pages'
          username: 'Sean H'
          email: 'sean.li.shin.ho@gmail.com'
